name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Extract version from Git
      id: get_version
      run: echo ::set-output name=version::$(git describe --tags --always --dirty)

    - name: Build the Docker image
      id: build
      run: |
        IMAGE_TAG=curioustinker/google-opensearch-api:${{ steps.get_version.outputs.version }}
        echo "::set-output name=image::$IMAGE_TAG"
        docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Push the Docker image
      run: |
        IMAGE_TAG=${{ steps.build.outputs.image }}
        docker push $IMAGE_TAG

    - name: Create a new release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        body: |
          This is an automated release generated from the GitHub Actions workflow.
        draft: false
        prerelease: false
