name: Docker Image CI

on:
  workflow_run:
    workflows: ["Upload Python Package"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Extract version from setup.py
      id: get_version
      run: echo ::set-output name=version::$(python -c "import re; with open('setup.py', 'r') as f: version = re.search(r'__version__ = \'([0-9\.]+)\'', f.read()).group(1); print(version)")

    - name: Build the Docker image
      id: build
      run: |
        VERSION=${{ steps.get_version.outputs.version }}
        IMAGE_TAG=curioustinker/google-opensearch-api:$VERSION
        LATEST_TAG=curioustinker/google-opensearch-api:latest
        
        echo "::set-output name=image_version::$IMAGE_TAG"
        echo "::set-output name=image_latest::$LATEST_TAG"
        
        docker build . --file Dockerfile --tag $IMAGE_TAG --tag $LATEST_TAG

    - name: Push the Docker image
      run: |
        IMAGE_VERSION=${{ steps.build.outputs.image_version }}
        IMAGE_LATEST=${{ steps.build.outputs.image_latest }}
        
        docker push $IMAGE_VERSION
        docker push $IMAGE_LATEST
