name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine

    - name: Build and publish
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
        twine upload --skip-existing --repository pypi dist/*
